version: '3.8'

services:
  # Analytics Backend - Spring Boot
  matcha-analytics-backend:
    image: openjdk:11
    container_name: matcha_analytics_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - BACKEND_PORT=5002
      - DB_HOST=mariadb
      - DB_PORT=3307
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "5002:5002"
    networks:
      - m-network-back

  # Analytics Frontend - React
  matcha-analytics-frontend:
    image: node:20-alpine
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: matcha_analytics_frontend
    env_file: .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
    ports:
      - "3002:3002"
    depends_on:
      - matcha-analytics-backend
    networks:
      - m-network-front

networks:
  m-network-back:
    external: true
  m-network-front:
    external: true 