services:
  # Analytics Backend - Spring Boot
  matcha-analytics-backend:
    image: openjdk:11
    container_name: matcha_analytics_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - BACKEND_PORT=5002
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=matcha
      - DB_PASSWORD=matcha
      - DB_NAME=matcha
      - SPRING_DATASOURCE_URL=jdbc:mysql://mariadb:3306/matcha?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=matcha
      - SPRING_DATASOURCE_PASSWORD=matcha
    ports:
      - "5002:5002"
    networks:
      - m-network-back

  # Analytics Frontend - React
  matcha-analytics-frontend:
    image: node:20-alpine
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: matcha_analytics_frontend
    env_file: .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
    ports:
      - "3002:3002"
    depends_on:
      - matcha-analytics-backend
    networks:
      - m-network-front

networks:
  m-network-back:
    name: m-network-back
    external: true
  m-network-front:
    name: m-network-front
    external: true
